image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - tag

variables:
  DRAFT: $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
  LATEST: $CI_REGISTRY_IMAGE:latest
  STABLE: $CI_REGISTRY_IMAGE:stable
  TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  RANCHER: $CI_REGISTRY/hoou/rancher-cicd:master
  PROXY_HTTP: http://proxy.hoou.ovh:3128
  PROXY_HTTPS: http://proxy.hoou.ovh:3128

before_script:
  -  docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build:
  stage: build
  script:
    - docker build
      --build-arg http_proxy=$PROXY_HTTP
      --build-arg https_proxy=$PROXY_HTTPS
      -t $DRAFT .
    - docker tag $DRAFT $LATEST
    - docker push $LATEST

tag:
  stage: tag
  only:
    - tags
  script:
    - docker tag $DRAFT $TAG
    - docker tag $DRAFT $STABLE
    - docker push $TAG
    - docker push $STABLE
